### ISSUE TITLE
Never ending launches

### ISSUE THREAD

**Issue by ekisielinski** [reportportal/agent-net-nunit#37]
Hi,

I have some problems with never ending launches in ReportPortal.

I run tests on Bamboo agent using ReportPortal plugin/integration (NUnit3).
(I don't know how it works, because I didn't configured it).

In my test, we can found something like this:

**1) create file sample.txt in NUnit3 test
2) TestContext.AddAtachments ("sample.txt")
3) delete sample.txt**

Now when test is finished, it does not finish launch.

There is an exception in Bamboo logs:

```
ReportPortal exception was thrown.
System.IO.FileNotFoundException: Could not find file '.....\sample.txt'.


   at ReportPortal.NUnitExtension.ReportPortalListener.FinishTest(XmlDocument xmlDoc)
   
ReportPortal exception was thrown.
System.ArgumentException: The tasks argument included a null value.
Parameter name: tasks
   at System.Threading.Tasks.TaskFactory.CheckMultiContinuationTasksAndCopy(Task[] tasks)
   at System.Threading.Tasks.TaskFactory`1.ContinueWhenAllImpl(Task[] tasks, Func`2 continuationFunction, Action`1 continuationAction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskFactory.ContinueWhenAll[TResult](Task[] tasks, Func`2 continuationFunction)
   at ReportPortal.Shared.Reporter.TestReporter.Finish(FinishTestItemRequest request)
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishSuite(XmlDocument xmlDoc)
```

**Comment by nvborisenko** [comment]
@ekisielinski please upgrade package. It will resolve issue with unfinished launches, in logs you will see warning that attached file doesn't exist.

Agent sends data asynchronously, kind of deferred mode. Use [this](https://github.com/reportportal/example-net-nunit/blob/master/src/Example/Tests/Class1.cs#L30) example how to properly send file. This way adds content of the file into "queue".
