### ISSUE TITLE
How to integrate ReportPortal with .net core

### ISSUE THREAD

**Issue by OlegYanushkevich** [reportportal/agent-net-nunit#39]
Hi, I want to migrate my tests from .net framework to .net core and I do not understand how to integrate the report portal with my tests. I read readme file and there it is somehow incomprehensibly described flow for .net core. Could you explain me it possible, and if yes, then how we can do it. Thanks!

**Comment by nvborisenko** [comment]
Actually .netcore is possible only with vstest runner and NUnit3TestAdapter nuget package. Reporting results to RP will be possible when new version of NUnit3TestAdapter package will be released (v3.14.0). It is not officially released yet, we are in awaiting of this version.

You can ask [here](https://github.com/nunit/nunit3-vs-adapter) what is planned date of release. Last time when I asked was end of April, might be they forgot to release it, not sure.

**Comment by ghost** [comment]
@nvborisenko, Thanks for your answer, but I'm trying to run my .net core tests via vstest runner and get next error:
`[7/5/2019 11:49:01 AM Error] Microsoft.VisualStudio.TestPlatform.Common.Exceptions.InvalidLoggerException: Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'ReportPortal'.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.TestLoggerManager.Initialize(String runSettings)
   at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform.CreateTestRunRequest(IRequestData requestData, TestRunCriteria testRunCriteria, TestPlatformOptions options)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(IRequestData requestData, TestRunCriteria testRunCriteria, ITestRunEventsRegistrar testRunEventsRegistrar, TestPlatformOptions options)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass18_0.<StartTestRun>b__0()`
 but if I'm using dotnet test, than all works fine. 

P.S my *.runsettings file:
![image](https://user-images.githubusercontent.com/28996736/60710752-13b46180-9f1c-11e9-8077-464ba438edc3.png)

it looks like `<TestAdaptersPaths>.</ TestAdaptersPaths>` doesn't connect needed adapter for ReportPortal. I assume that the studio does not run tests from the working directory of the project.
maybe you met this?

**Comment by nvborisenko** [comment]
To do it, what you wanted, you need use https://github.com/reportportal/agent-net-vstest agent.

If you already use it please share the list of installed nuget packages and the version of Visual Studio. It works for me with v16.1.1. Not sure, this magic is supported beginning v15.9.

**Comment by ghost** [comment]
@nvborisenko 
![image](https://user-images.githubusercontent.com/28996736/60726170-97ce0f80-9f43-11e9-9fcd-853972d92855.png)
![image](https://user-images.githubusercontent.com/28996736/60726189-a7e5ef00-9f43-11e9-8d1c-dd81c48daabc.png)

**Comment by nvborisenko** [comment]
Please share your config file. I reproduced your issue if `url` parameter is incorrect.

**Comment by ghost** [comment]
@nvborisenko 
![image](https://user-images.githubusercontent.com/28996736/60788254-f0c8be00-a164-11e9-8c5e-25bcc5d3df4e.png)
