### ISSUE TITLE
Issue with RPv5 - The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Seploid** [reportportal/agent-net-nunit#66]
It looks that in some cases ReportPortal Client cannot setup secure channel with new Report Portal v.5 - https://reportportal.epam.com
To integrate with RP v5 I've updated ReportPortal.NUnit to 4.0.0 version. 

Everything works fine on my local PC, but there is an issue when I execute tests on VM of a customer (Windows Server 2012 R2):
1) I don't see test run in RP,
2) On the console I see the following error in the end of run:

Finishing to send the results to Report Portal... ReportPortal exception was thrown.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.Resources.ServiceBaseResource.<SendHttpRequestAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.Resources.ServiceBaseResource.<SendAsJsonAsync>d__11`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.Resources.ServiceBaseResource.<PostAsJsonAsync>d__8`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Client.Resources.ServiceLaunchResource.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.<ExecuteAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.<ExecuteAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass22_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(String report)

Could you please investigate this issue?

**Comment by nvborisenko** [comment]
Recommended way is upgrading Windows Server 2012: https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

I'm not sure whether we can do something on agent/client side.

**Comment by Seploid** [comment]
@nvborisenko Yes, the previous version works fine. I will check TLS protocols on the VM as it is mentioned by your link.

**Comment by nvborisenko** [comment]
Please reach me out in internal epam communication channel (mikalai barysenka).
