### ISSUE TITLE
Unable to integrate ReportPortalNUnit V4.3.1 with server version build: 4.3.6

### ISSUE THREAD

**Issue by mihai-metro** [reportportal/agent-net-nunit#80]
I would like to start by saying that the server is not under my administration and for the moment I can't upgrade it. 

After following the steps from this repository I do get the error:
ReportPortalListener Error: 0 : 23:13:58.7863904 : 1-testhost : ReportPortal exception was thrown.
ReportPortal.Client.ReportPortalException: Response status code does not indicate success: BadRequest (400) POST http://10.97.177.235:8080/api/v1/mposair/launch
 ---> System.Net.Http.HttpRequestException: Response message: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
   --- End of inner exception stack trace ---
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent)
   at ReportPortal.Shared.Internal.Delegating.BaseRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttemptCallback, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Internal.Delegating.ExponentialRetryRequestExecuter.ExecuteAsync[T](Func`1 func, Action`1 beforeNextAttempt, IStatisticsCounter statisticsCounter)
   at ReportPortal.Shared.Reporter.LaunchReporter.<>c__DisplayClass25_0.<<Start>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at ReportPortal.Shared.Reporter.LaunchReporter.Sync()
   at ReportPortal.NUnitExtension.ReportPortalListener.FinishRun(String report) in C:\projects\agent-net-nunit\src\ReportPortal.NUnitExtension\ReportPortalListener.Launch.cs:line 113

I did a bit of research and I know about the major release to V5, sadly I can not upgrade my server. Is there any workaround for this problem?

Thank you

**Comment by nvborisenko** [comment]
@mihai-metro the latest version of `ReportPortal.NUnit` agent is `3.7.15` compatible with your RP server. Starting from version `4.0.0+` agent supports only RP server `5.0.0+`.
